"""
Shared helpers for the Helm-template to Compose compiler.
"""

from __future__ import annotations

import base64
import binascii
import logging
import re
import shlex
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import TYPE_CHECKING

from ruamel.yaml import YAML
from yaml import CSafeLoader, MappingNode, load_all

from composer.exceptions import CompilationError

if TYPE_CHECKING:
    from typing import Any


log = logging.getLogger(__name__)


def make_yaml(*, allow_duplicate_keys: bool = False) -> YAML:
    """
    Create a ruamel.yaml parser/emitter with stable formatting.

    Args:
        allow_duplicate_keys (bool): Whether duplicate mapping keys should be accepted.

    Returns:
        YAML: YAML instance configured for block-style Compose output.
    """
    yaml = YAML()
    yaml.allow_duplicate_keys = allow_duplicate_keys
    yaml.default_flow_style = False
    yaml.indent(mapping=2, sequence=4, offset=2)
    if allow_duplicate_keys:
        log.info("Configured YAML parser option=allow_duplicate_keys")
    return yaml


def to_plain_data(value: Any) -> Any:
    """
    Convert ruamel.yaml containers into plain Python containers.

    Args:
        value (Any): YAML-loaded value.

    Returns:
        Any: Plain dictionaries, lists, and scalar values.
    """
    if isinstance(value, Mapping):
        return {str(key): to_plain_data(item) for key, item in value.items()}
    if isinstance(value, Sequence) and not isinstance(value, (str, bytes)):
        return [to_plain_data(item) for item in value]
    return value


def decode_base64_text(value: str) -> tuple[str, bool]:
    """
    Decode a base64 text value when it can be represented as UTF-8.

    Args:
        value (str): Source text value that may be base64 encoded.

    Returns:
        tuple[str, bool]: Decoded value and whether base64 decoding was applied.
    """
    compact_value = "".join(value.split())
    try:
        decoded_bytes = base64.b64decode(compact_value, validate=True)
        return decoded_bytes.decode("utf-8"), True
    except (binascii.Error, UnicodeDecodeError):
        return value, False


def render_env_sh(values: dict[str, str]) -> str:
    """
    Render exported environment variables as a shell source file.

    Args:
        values (dict[str, str]): Environment variable values keyed by variable name.

    Returns:
        str: Shell source file content with exported variables.
    """
    lines = [
        "#!/usr/bin/env bash",
        "# Generated by composer.entrypoint.",
        "# Source this file before running docker compose:",
        "#   source ./.env.sh",
        "",
    ]
    for key in sorted(values):
        lines.append(f"export {key}={shlex.quote(values[key])}")
    lines.append("")
    return "\n".join(lines)


def write_text_file(path: Path, content: str) -> None:
    """
    Write a text file, creating parent directories when needed.

    Args:
        path (Path): Output file path.
        content (str): Text content to write.

    Returns:
        None: The output file and its parent directory exist.
    """
    log.info("Writing file path=%s bytes=%s", relative_to_cwd(path), len(content))
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


def write_generated_files(root: Path, files: dict[Path, str]) -> None:
    """
    Write generated support files below a root directory.

    Args:
        root (Path): Directory under which generated files should be written.
        files (dict[Path, str]): Generated file content keyed by relative path.

    Returns:
        None: Generated support files have been written.
    """
    log.info(
        "Writing generated support files root=%s count=%s",
        relative_to_cwd(root),
        len(files),
    )
    for rel_path, content in files.items():
        output = root / rel_path
        log.info("Writing generated support file path=%s", relative_to_cwd(output))
        output.parent.mkdir(parents=True, exist_ok=True)
        repair_generated_file_path(output)
        output.write_text(content)


def repair_generated_file_path(path: Path) -> None:
    """
    Remove an empty generated directory that should be a file.

    Docker can create bind-mount sources as directories when a generated file is
    missing before ``docker compose up``. This repairs that exact empty
    directory case and leaves non-empty directories alone.

    Args:
        path (Path): Generated file path about to be written.

    Returns:
        None: Conflicting generated filesystem entries have been repaired.
    """
    if not path.is_dir():
        return
    if any(path.iterdir()):
        raise IsADirectoryError(path)
    log.info(
        "Removing empty generated directory path=%s reason=expected-file",
        relative_to_cwd(path),
    )
    path.rmdir()


def as_dict(value: Any) -> dict[str, Any]:
    """
    Return a dictionary value or an empty dictionary fallback.

    Args:
        value (Any): Value to coerce.

    Returns:
        dict[str, Any]: Original dictionary value or an empty dictionary.
    """
    return value if isinstance(value, dict) else {}


def as_list(value: Any) -> list[Any]:
    """
    Return a list value or an empty list fallback.

    Args:
        value (Any): Value to coerce.

    Returns:
        list[Any]: Original list value or an empty list.
    """
    return value if isinstance(value, list) else []


def is_non_string_sequence(value: Any) -> bool:
    """
    Return whether a value is a sequence but not text or bytes.

    Args:
        value (Any): Value to inspect.

    Returns:
        bool: True when the value is a non-string sequence.
    """
    return isinstance(value, Sequence) and not isinstance(value, (str, bytes))


def as_str(value: Any) -> str:
    """
    Return a string value with ``None`` mapped to an empty string.

    Args:
        value (Any): Value to stringify.

    Returns:
        str: String representation, or an empty string for ``None``.
    """
    if value is None:
        return ""
    return str(value)


def scalar_to_env_value(value: Any) -> str:
    """
    Convert a scalar-like value into a Compose environment string.

    Args:
        value (Any): Scalar-like value from Kubernetes YAML.

    Returns:
        str: Compose-compatible environment variable value.
    """
    if value is None:
        return ""
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


def rewrite_base_hostname_text(
    value: str,
    source_base_hostname: str,
    target_base_hostname: str,
) -> str:
    """
    Replace occurrences of one rendered base hostname with another.

    Args:
        value (str): Text that may contain the rendered base hostname.
        source_base_hostname (str): Hostname emitted by the rendered manifests.
        target_base_hostname (str): Hostname to emit in compiled output.

    Returns:
        str: Text with the target base hostname substituted.
    """
    if not source_base_hostname or not target_base_hostname:
        return value
    if source_base_hostname == target_base_hostname:
        return value
    return value.replace(source_base_hostname, target_base_hostname)


def sort_dict(value: dict[str, str]) -> dict[str, str]:
    """
    Return a dictionary sorted by key for stable output.

    Args:
        value (dict[str, str]): Dictionary to sort.

    Returns:
        dict[str, str]: Dictionary rebuilt in sorted key order.
    """
    return {key: value[key] for key in sorted(value)}


def unique_list(values: list[str]) -> list[str]:
    """
    Return list values with duplicates removed while preserving order.

    Args:
        values (list[str]): Values to deduplicate.

    Returns:
        list[str]: Deduplicated values in first-seen order.
    """
    seen: set[str] = set()
    result: list[str] = []
    for value in values:
        if value in seen:
            continue
        seen.add(value)
        result.append(value)
    return result


def normalize_env_part(value: str) -> str:
    """
    Convert arbitrary text into a shell-safe environment variable name.

    Args:
        value (str): Raw text to normalize.

    Returns:
        str: Shell-safe environment variable fragment.
    """
    value = re.sub(r"[^A-Za-z0-9]+", "_", value).strip("_").upper()
    if not value:
        return "VALUE"
    if value[0].isdigit():
        value = f"_{value}"
    return value


def normalize_compose_name(value: str) -> str:
    """
    Convert arbitrary text into a Compose-friendly service or volume name.

    Args:
        value (str): Raw text to normalize.

    Returns:
        str: Compose-friendly lower-case name.
    """
    value = re.sub(r"[^a-zA-Z0-9_-]+", "-", value).strip("-").lower()
    return value or "service"


def normalize_path_part(value: str) -> str:
    """
    Convert arbitrary text into a safe generated file path component.

    Args:
        value (str): Raw text to normalize.

    Returns:
        str: File path-safe component.
    """
    value = re.sub(r"[^a-zA-Z0-9_.-]+", "_", value).strip("._")
    return value or "value"


def relative_to_cwd(path: Path) -> str:
    """
    Return a path relative to the current working directory when possible.

    Args:
        path (Path): Path to format.

    Returns:
        str: Relative path when possible, otherwise the original path string.
    """
    try:
        return str(path.resolve().relative_to(Path.cwd()))
    except ValueError:
        return str(path)


class ManifestLoader(CSafeLoader):
    """
    Parse rendered manifests quickly while rejecting ambiguous duplicate fields.
    """

    def construct_mapping(self, node: MappingNode, deep: bool = False) -> dict[Any, Any]:
        """
        Construct an object without silently overwriting duplicate keys.

        Args:
            node (MappingNode): Parsed YAML object node.
            deep (bool): Whether child objects should be fully constructed.

        Returns:
            dict[Any, Any]: Constructed YAML mapping.

        Raises:
            CompilationError: The document contains a duplicate mapping key.
        """
        explicit = [
            self.construct_object(key, deep=deep)
            for key, _ in node.value
            if key.tag != "tag:yaml.org,2002:merge"
        ]
        if len(explicit) != len(set(explicit)):
            raise CompilationError("Duplicate YAML mapping key")
        self.flatten_mapping(node)
        return super().construct_mapping(node, deep=deep)


def load_documents(text: str) -> list[object]:
    """
    Read YAML documents using the safe C parser and duplicate-key validation.

    Args:
        text (str): YAML input stream.

    Returns:
        list[object]: Parsed documents without formatting metadata.

    Raises:
        CompilationError: A mapping contains duplicate fields.
        yaml.YAMLError: The input is malformed YAML.
    """
    return list(load_all(text, Loader=ManifestLoader))
